### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by palmaresk8** [terna/SLAPP#1]
You don't need to create a branch for each small update. A repository usually has one or two branches (eg. a 'master' branch and a 'dev' branch). You just have to commit the code and use tags to identify the version of the code. Doing this way, it will be available in the releases tab (https://github.com/terna/SLAPP/releases).

This kind of model (one branch for each small tag) is difficult to track, because we have to checkout the correct branch every time a small update (tag) is issued.

**Comment by terna** [comment]
Fixed, many thanks, Pietro (now I've SLAPP2 and SLAPP3 with uniquely the master branch.
